feat: DB connection & endpoints
FIarlori/Server-with-NoSQLdatabase pull request #1
Opened 2022-02-21 12:23 UTC by FIarlori

2022-02-22 13:19 UTC, diazmaira requested changes

2022-02-22 13:19 UTC, diazmaira commented on README.md
> +## Install
This is `Prerequisite` (things you need before the server runs) instead of `Install`.
Let the user choose how he will download `nodejs` instead of specifying how to install it

2022-02-22 13:19 UTC, diazmaira commented on README.md
>    POST request in Postman to `"http://localhost:3000//questionnaire"`
You have two slash `//`in line 16 and 17. Should be just one

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +        required: true,
Please add a message when the field is not required. https://mongoosejs.com/docs/validation.html

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +      time: { type: String },
Add more validations:
1. when the field is required
2. validate value with regular expresion (time format "00:00")  [regex example](https://stackoverflow.com/questions/21842694/mongoose-validation-required-false-validate-regex-issues-with-empty-value)

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +        goToBed: { type: String, required: true },
Add one more validation:
1. validate string with regular expresion (time format "00:00")  [regex example](https://stackoverflow.com/questions/21842694/mongoose-validation-required-false-validate-regex-issues-with-empty-value)

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +        wakeUp: { type: String, required: true },
Add one more validation:
1. validate string with regular expresion (time format "00:00")  [regex example](https://stackoverflow.com/questions/21842694/mongoose-validation-required-false-validate-regex-issues-with-empty-value)

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +        total: { type: Number, required: true },
Add more validations:
1. Can `total` be a negative number? Can be zero? 
2. Add message when validations are wrong 
https://mongoosejs.com/docs/validation.html

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +      socialNetworkVideoGames: Boolean,
Add more validations:
1. it should be required.
2. response message when validations are wrong

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +      tool: {
Add more validations:
1. it should be required
2. response message when validations are wrong

2022-02-22 13:19 UTC, maira1001001 commented on models/Mongoschema.js
> +      beforeSleep: {
Add more validations:
1. it should be required
2. response message when validations are wrong

2022-02-22 13:19 UTC, diazmaira commented on models/Mongoschema.js
> +      frecuency: {
Add more validations. For each property of `frequency`:
1. it should be required
2. Can this number be negative? (min, max) https://mongoosejs.com/docs/validation.html#built-in-validators
3. Add default value https://mongoosejs.com/docs/api.html#schematype_SchemaType-default
4. Response message when validations are wrong

2022-02-22 13:19 UTC, maira1001001 commented on package.json
> +    "body-parser": "^1.19.1",
You are not using this module. You can remove it.

2022-02-22 13:19 UTC, diazmaira commented on package.json
> +    "nodemon": "^2.0.15"
`nodemon` is a devDependency because it is used for development purposes.

2022-02-22 13:19 UTC, diazmaira commented on router/routes.js
> +    mongoose.connect(uri); //TODO: ask for connection status ¿await mongoose.authenticate().then(() =>?
It should return the database status. So, you don't need to connect again with the database. Check this function:
```
const mongoose = require('mongoose');
...
mongoose.STATES[mongoose.connection.readyState]
```

2022-02-22 13:19 UTC, maira1001001 commented on router/routes.js
> +    res.status(200).set('Content-Type', 'application/json').send(questionnaire);
What happens when database validation fails? You should return `400` status code instead of  `500`

2022-02-24 15:24 UTC, FIarlori commented on models/Mongoschema.js
> +        required: true,
Didn't you mean: "when the field IS required" ?

2022-03-01 16:37 UTC, maira1001001 requested changes

2022-03-01 16:37 UTC, maira1001001 commented on models/Mongoschema.js
> +              return (!v || !v.trim().length) || time.test(v)
What happen when the value `v` is `undefined` ? and when `v is ""`? Are them valid values for `goToBed`?

2022-03-01 16:37 UTC, maira1001001 commented on models/Mongoschema.js
> +              return (!v || !v.trim().length) || time.test(v)
Same comment as line `18`.

2022-03-01 16:37 UTC, maira1001001 commented on router/routes.js
>  // GET /health --> returns database status
In order to add comments to the endpoints, follow the standard https://apidocjs.com/

2022-03-01 16:37 UTC, maira1001001 commented on router/routes.js
>  // POST /questionnaire --> receives the questionnaire and stores it in the database
In order to add comments to the endpoints, follow the standard https://apidocjs.com/

2022-03-01 16:37 UTC, maira1001001 commented on router/routes.js
>  // GET /questionnaire/id: --> returns the questionnaire
In order to add comments to the endpoints, follow the standard https://apidocjs.com/

2022-03-01 16:37 UTC, maira1001001 commented on router/routes.js
> +    res.status(400).set('Content-Type', 'application/json').send(error);
Sorry, It was my mistake: `500` was the right answer :ok_hand: . We use `400` when the **client** makes a bad request (e.g.: payload incomplete) and the **server** will not process or continue with the request. `400` status code is a client error.
So in this case, when database operation failed for some reason, it is a server error, not a client error.

2022-03-01 16:37 UTC, maira1001001 commented on router/routes.js
> +    console.log(req.params, "params");
`console.log` is for debugging purpose. Please remove it. We will implement `logs` in a different why in order to follow the flow a request

2022-03-01 18:25 UTC, maira1001001 reviewed
I edited a comment.

2022-03-03 13:15 UTC, AgustinRow commented on .eslintrc.json
> +  "parser": "@babel/eslint-parser",
You are calling the parser with babel and then you are not using it. Either remove it or change your code to fit your specifications (I mean `import` or `export` syntax)

2022-03-03 13:15 UTC, AgustinRow commented on package.json
> +    "@babel/core": "^7.17.3",
Babel is a transpiler. It transpile Ecmascript6 code(syntax sugar) that node does not understand, so that way the chrome V8 engine could execute it. 
If you are not using it should be removed

2022-03-14 11:27 UTC, maira1001001 reviewed
Our main purpose for "logs" is **debugging**. Here are some principles to follow:

- For **debugging reasons**: we should log each from HTTP request to HTTP response following the flow.  
- For **gain visibility**: Devs can understand what is happening when executing the code 

1. _What should I log?_ Whatever you believe necessary, but at least the **whole flow,** which implies the **function names** with its **inputs** and its **outputs**. Remember to also log database operations.
2. _Where should I log?_ into the standard output and standard error. You can choose what it is convenient for you. standards output examples: console, database, files.
3. _When should I log?_ Use **levels** to log when it is necessary. Different environments (dev, testing, prod, etc) require different kind of logs. You should not remove logs when changing environments.

2022-03-14 19:23 UTC, FIarlori commented on models/Mongoschema.js
> +        total: { type: Number, required: true },
1. Applied change so that 'value must be 0 or bigger'.

2022-03-14 19:26 UTC, FIarlori commented on models/Mongoschema.js
> +      frecuency: {
2. Applied change so that 'value must be 0 or bigger'.

2022-03-14 19:38 UTC, FIarlori commented on models/Mongoschema.js
> +              return (!v || !v.trim().length) || time.test(v)
Those are not valid values for goToBed. When that happens it sends the following message:  "bedtime must be indicated".

2022-03-14 19:55 UTC, FIarlori commented
feature/MongoDB-server merge

2022-03-14 20:05 UTC, merged